PMPHArMFVEJPaGLKAW.@AWGVMTPMKJmJPLALAEVPKBPLAGMP]SLAVAPVE@MPMKJIAAPWPLATQHWAKBIK@AVJHMBAAGLKAWKBRMFVEJPIAHK@MAW@EJGAPLVKQCLPLAWPVAAPW
.TVKITPaJAVCAPMGBQWMKJKBPVE@MPMKJEHVL]PLIWEJ@IK@AVJFAEPWHMRAH]TAVGQWWMKJIAHK@MGWPVMJCW@]JEIMGPAITKSMPLEVE@MEJPEJ@QTHMBPMJCRMFAIEHAEJ@BAIEHARKGEHTHE]BQHEJ@WTMVMPA@.GKRAVeVPtVKITPeFQWPHMJCGMP]WGETAMJPAVPSMJA@SMPLPVE@MPMKJEHIKPMBWRMFVEJPGKHKVWFHAJ@MJCSMPLJAKJHMCLPWE@]JEIMGEJ@HMRAH]WGAJASMPLEIK@AVJPSMWPBQHHKBAJAVC]EJ@IKRAIAJP.WB\GMP]LQWPHAVL]PLIMGGHETWWPVMJCTHQGOWEIFMAJPGVKS@JKMWARMFVEJPTAVGQWWMKJ.RKGEHWIEHAEJ@BAIEHARKGEHHMRAH]EJ@WTMVMPA@SMPLPVE@MPMKJEHMJBHQAJGAW@]JEIMGEJ@AJCECMJC.RKGEHWwPVQGPQVA@TKTBQWMKJPVEGOSMPLERMFVEJPMJPVKEJ@AJAVCAPMGKQPVKMJGHQ@MJCVL]PLIMG@VKTWSMPLIAHK@MGIEHAEJ@BAIEHARKGEHW.OA]SKV@WTKTBQWMKJSKVH@IQWMGPVE@MPMKJEHAHAIAJPWIK@AVJFAEPWRMFVEJPRMFAWAJAVCAPMGHMRAH]BQWMKJJAKJHMCLPWGQHPQVEHFHAJ@GMJAIEPMGWKQJ@PVEGO.GK@AjEIArMHHAPPA.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]wEMVEPJEaJPAVPEMJIAJP	wqj`eveXƒÄúƒÄÇƒÄîXcEQPEIMtEPMHXjMGOwLMJ@AXwKJEHMwKJESEJAXvEQPXvKLMPjECFLM@A
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVr.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVK	vL]PLIMGtQHWAy..RAVWA	qVFEJ`EJGAy.mJPLAWPVAAPWSLAVAAGLKAWTHE].gKHKVWFHAJ@MJVL]PLIMGWSE].pVE@MPMKJSLMWTAVWSMPLIK@AVJBHEMV.rMFVEJPAGLKAWBMHHPLAEMV
..tVA	gLKVQW	cEPLAVMJCfAEPy.KKKKK.gHETPKPLALAEVPFAEPBAAHPLABHKS.MMMMMM.wPATWMJPMIAEWPLAGMP]CHKSW
..gLKVQW	rMFVEJPbQWMKJy.SKKKKKKK.`EJGAPLVKQCLPLAHMCLPQJ@AVPLAJAKJWOMAW.KKKK.bAAHPLAVL]PLISLAVAPLAPVE@MPMKJHMAW
..fVM@CA	gQHPQVEHsLMWTAVy.kH@IAAPWJASMJERMFVEJP@EJGA.lMWPKV]EJ@BQPQVAMJEBHAAPMJCCHEJGA
.WLLLLLL.KKKKKK..KQPVK	aGLKAWbE@Ay.gMP]HMCLPW@MIFQPPLAAGLKAWWPE].mJPLALAEVPSLAVAPVE@MPMKJEJ@IK@AVJMP]THE]
..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
