PMPHAw]ITLKJ]KBaGLKAWwMJBKJÁâE@AaGKW.@AWGVMTPMKJeNKQVJA]PLVKQCLPMIAEJ@WTEGASLAVAAGLKAWKBPLATEWPGVAEPAEW]ITLKJ]KBPLATVAWAJP
mJWTMVA@F]PLALEVIKJMKQWRMFAWKBeJ@VASvE]AH
.TVKITPaJAVCAPMGAHAGPVKJMGPVEJGAQTHMBPMJCIAHK@MAW@VMRMJCFAEPWAQTLKVMGW]JPLHE]AVWTQHWEPMJCFEWWHMJAEPIKWTLAVMGTE@WIEHAEJ@BAIEHARKGEHWAPLAVAEHEJ@TKSAVBQH.GKRAVeVPtVKITPbQPQVMWPMGGMP]WGETAJAKJHMCLPWVABHAGPMJCKJVEMJ	WHMGOWPVAAPWRMFVEJPGKHKVWWHAAOEJ@IK@AVJSMPLEGKWIMGPKQGLLMCL	PAGLRMFA.WB\APLAVAEHSMJ@GLMIAW@MCMPEHWTEVOHAWLAEVPFAEP	HMOAFEWWPLQITWGKWIMGSLKKWLAW.RKGEHWIEHAEJ@BAIEHARKGEHWAPLAVAEHLEVIKJMAWTKSAVBQHEJ@QTHMBPMJC.RKGEHWwPVQGPQVA@PVEJGAWPATPVEGOSMPLEJMJWTMVMJCMJPVKEJ@AQTLKVMG@VKTWBAEPQVMJCAPLAVAEHIEHAEJ@BAIEHARKGEHW.OA]SKV@WPVEJGAQTHMBPMJCAHAGPVKJMGA@IEJ@VASVE]AHLEVIKJMKQWJAKJRMFAWGKWIMGNKQVJA]W]JPLSERABQPQVAFAEPWAJAVC]@VMRAJWKQJ@PVEGO.GK@AjEIAwHEQCLPAVLKQWA	bMRA.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]eJ@VASvE]AH	bMJ@}KQVlEVIKJ]aTMWK@A
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVw.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVK	w]JPLsERAy..FQMH@	QTy..RAVWA	gKWIMGnKQVJA]y.wPEVWEHMCJMJPLAJMCLP.sLMWTAVWKBPMIAEJ@HMCLP.pLVKQCLAGLKAWSABMJ@KQVSE].mJPLA@EJGAKBPLAGKWIMGTHE]
.KKKKKMMMMMM..tVA	gLKVQW	sERAKBlEVIKJ]y.bAAHPLATQHWAPLAAJ@HAWWFAEP.mJPLAVL]PLISAVAGKITHAPA
.ELLLL..gLKVQW	gAHAWPMEHfQVWPy.aQTLKVMEMJPLAEMV.lEVIKJ]ARAV]SLAVA
.SKKKKKMMMMMM..fVM@CA	pAITKVEH`VMBPy.hKWPMJPLABHKS.pMIAIKRAWWHKS
.WLLLLLLKKKKKK..KQPVK	aGLKAWbE@Ay.pLVKQCLPLAAGLKAWSAVAIEMJ
.lEVIKJ]MWKQVVABVEMJ
.^^^^^^..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
