C^C[R
cXBT_XQs^A^YRzRETNdRYCB_VY|REV_^ZVY~[V_^=SRDTE^GC^XY
vPRYC[R@_^DGREXQC_RQXERDC@_RERS^A^YR[^P_CSVYTRDC_EXBP_[RVARD^YDG^ERSUNC_RE_NC_ZDXQZRETNVYSPEVTR=GEXZGC
vZU^RYCDG^E^CBV[DXBYSDTVGRRC_RERV[T_^ZRDDXXC_^YP_VEZXY^RDPRYC[RVTXBDC^TCROCBERDERQ[RTC^ARVCZXDG_RERTV[Z^YPZR[XS^RDDRERYR^YDCEBZRYCV[ZV[RVYSQRZV[RAXTV[_VEZXY^RDGRVTRQB[CEVYFB^[ZXXS=TXAREvECgEXZGC
s^A^YR[^P_CTVDTVS^YPC_EXBP_VCEVYFB^[QXERDCRC_RERV[P[X@DXQCZ^DCDRERYRVYSDG^E^CBV[VZU^VYTRTXYCRZGXEVENVYSGRVTRQB[A^DBV[D=DQO
DXQC@^YST_^ZRDPRYC[REBDC[^YP[RVARDS^DCVYCT_X^ERT_XRDQ[X@^YP@VCREDBUC[RTR[RDC^V[_BZ=AXTV[D
ZV[RVYSQRZV[RAXTV[_VEZXY^RDDXQCVYSDXXC_^YPVYPR[^TVYSTV[Z^YP=AXTV[DdCEBTCBERS
VZU^RYCDCRGCEVT\@^C_GRVTRQB[^YCEXVYSPRYC[RXBCEX^YT[BS^YPDXQC^YDCEBZRYCV[[VNRED@^C_DRERYRQRZV[RVYSZV[RAXTV[_VEZXY^RD=\RN@XESD
VZU^RYCDG^E^CBV[YR@VPR^YDCEBZRYCV[DRERYRZRS^CVC^ARTV[Z^YPRC_RERV[DVTERSCEVYFB^[sVY^R[zVY^\S^A^YRZRETNDRERY^CNGRVTRQB[A^URDTXYCRZG[VC^AR=TXSRyVZR
c_ReV^YUX@cEXXGD=UGZ
=PRYER~YGBC
=GEXZGC~YGBC
cEVT\^YDG^ERSUNsVY^R[zVY^\sxv|xexy|v{vpb|rev~zvy~{{v~bDRD^Z^[VEZBD^TV[A^URZXXSDCN[RPRYER^YDCEBZRYCD=[RCCRE
c=^YT[BSRaXTV[
qV[DR=VGGaRED^XY
A=SBEVC^XY
==[NE^TD
l^YCEXPRYC[R@^YSj=dXQCT_^ZRD=XXXXXX=lAREDRqXERDC{^P_Cj=`_^DGRED^YC_R[RVARD=rT_XRDXQZRETNDCXBT_==lt_XEBDs^A^YRrZUEVTRj=v______=pEVTRQ[X@DPRYC[N==luE^SPRtR[RDC^V[VEZXYNj=dXQCT_X^E=XXXXXX={^P_CC_EXBP_C_RCERRD=ZZZZZZ==lXBCEXcEVYFB^[qVSRj=gRVTR^YC_RD^[RYTR=V_______==tERVCRSUNvcg[VNRE=_CCGD@@@VCG[VNRETXZ==tXGNE^P_Cõžv\C^D~YT