PMPHApM@AWKB`AGATPMKJ.@AWGVMTPMKJeNKQVJA]PLVKQCLPLAWLE@KSWSLAVA@AGATPMKJHMAWFAJAEPLPLAWQVBEGAMJWTMVA@F]PLAAJMCIEPMGEJ@GKITHA\PEHAWKBpLApEHAJPA@iV
vMTHA]
pLAPVEGOGETPQVAWEWAVAJA]API]WPAVMKQWRMFAVAIMJMWGAJPKBEPSMHMCLPKGAEJ
.TVKITPeIFMAJPWKQJ@WGETAAPLAVAEHPA\PQVAWLEQJPMJCIAHK@MAWHE]AVA@W]JPLWCAJPHATAVGQWWMKJAIKPMKJEH@ATPLWAVAJAEPIKWTLAVAWKKPLMJCBAIEHARKGEHMJPVKWTAGPMRAEJ@I]WPAVMKQWIKK@.GKRAVeVPtVKITPeI]WPAVMKQWGKEWPEHHEJ@WGETAEPPSMHMCLPSERAWGVEWLMJCECEMJWPGHMBBWAPLAVAEHCHKSIK@AVJEJ@WQVVAEHWP]HA@VAEIHMOAEJ@RMWQEHH]GETPMREPMJCSMPLELMJPKBI]WPAV].WB\KGAEJSERAW@MWPEJPPLQJ@AVWKBPSMJ@GLMIAWEIFMAJPAGLKAWWQFPHASLMWTAVW.RKGEHWBAIEHARKGEHAPLAVAEHEJ@LEQJPMJCWKBPLEVIKJMAWSLMWTAV	HMOAPKJAWAIKPMKJEHVAWKJEJGA.RKGEHWwPVQGPQVA@EIFMAJPPVEGOSMPLWAVAJAMJPVKEJ@TAEGABQHKQPVKSMPLLEQJPMJCIAHK@MGBAIEHARKGEH.OA]SKV@WEIFMAJPAPLAVAEHWKQJ@WGETALEQJPMJCI]WPAVMKQWGMJAIEPMGWAVAJA@VAEIHMOAAHAGPVKJMGGLMHH@AGATPMKJPSMHMCLPKGAEJWKQJ@PVEGO.GK@AjEIApLApEHAJPA@iV
vMTHA].FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]fEVFEE@vATVMWA	bAIEHAXbQHHwKJCXwEM]EEVEXeLEEJtEJ@E]eJAAPtE@@EXpLAvMWLwLMHTEvEK
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVp.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVK	WKBPSERAWy..RAVWA	CAJPHAAGLKAWy..SLMWTAVA@GLKVQWy.KKKKKKK.MMMMMMMMMMM..FVM@CA	WAVAJA@VMBPy..KQPVK	BE@AMJPKIMWPy..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
