LQLT]}[PW]KW^LP]|YV[]^TWWJ}[PWKNWUlYVBZW\]V2\]K[JQHLQWVqVLP]TYZAJQVLPW^JPALPU][PW]K_MQ\]LP]KL]HKqVKHQJ]\ZALP]LQU]T]KK\YV[]W^^WJUKYV\KPY\WOK2HJWUHL}V]J_]LQ[PQHPWHQVKLJMU]VLYTNQZJYVLKAVLPTYA]JKQV^][LQWMKJPALPUMHZ]YLH]J[MKKQWV\JQNQV_ZYKKTQV]\AVYUQ[ZJ]YSKOQLPYHTYA^MT^]UYT]NW[YTYV\\]]H_JQLLAUYT]NW[YT2[WN]JyJLhJWUHL~MLMJQKLQ[\YV[][TMZK[]V]OQLPNQZJYVLTQ_PLKPWTW_JYHPQ[\QKHTYAKYV\]V]J_]LQ[\YV[]JKUW\]JVYV\KT]]SOQLPYK[Q^QLOQKLV]WV[WTWJKYV\\AVYUQ[UWLQWV2K^@ZYKKLPMUHKKAVLPKOQJTK[JWO\YUZQ]V[]JPALPUQ[[TYHK2NW[YTKHTYA^MT^]UYT]NW[YT\]]H_JQLLAUYT]NW[YT]V]J_]LQ[\]TQN]JA2NW[YTKkLJM[LMJ]\PQHPWHKL]HLJY[SOQLP_WW\QVLJWYV\VQ[]WMLJWQV[TM\QV_KWU]\JWHKOQLPHTYA^MT^]UYT]YV\_JQLLAUYT]NW[YTK2S]AOWJ\KPQHPWHQVKLJMU]VLYT\YV[]HWH]T][LJWVQ[JPALPUQ[NQZ][TMZV]WV^MLMJQKLQ[_JWWNA\AVYUQ[
		2[W\]vYU]vYJBQKKMV\WT\UMV\2ZHU	2_]VJ]qVHML2HJWUHLqVHMLlJY[SQVKHQJ]\ZAjPALPUQKY\YV[]JPQHPWHQVKLJMU]VLYT
		mK]KQUQTYJUMKQ[YTNQZ]UWW\KLAT]_]VJ]QVKLJMU]VLK2T]LL]Jv2QV[TM\]nW[YT~YTK]2YHHn]JKQWVN

		2\MJYLQWV


22TAJQ[KcQVLJWZ]YLe22cN]JK]e2qVLP]][PWQV_PYTTK2jPALPUKH]YSKQV[W\]K2|YV[]^TWWJOPQKH]JK2qVLP]V]WV_TWO22chJ]{PWJMKe2WWWWW2QQQQQQ22c{PWJMKe2kL]HKYTQ_VKPY\WOKU]J_]2qVLP]HMTK]W^TQ_PL2o]^QV\WMJMJ_]22czJQ\_]e2y\YV[]Z]AWV\LQU]2qVLP]TYA]JKW^KWMV\2tWKLYV\^WMV\22cWMLJWe2WWWW2}[PW]K^Y\]ZMLLP]JPALPUKLYAKÚ¸ž22{J]YL]\ZAylhTYA]J2PLLHKOOOYLHTYA]J[WU22{WHAJQ_PLú‘

ySLQKqV[