SNSKBrI^NBKCNI@bDOHBT-CBTDUNWSNHIfUBKBISKBTTEBFSBDOHBTSOUHR@OSOBIN@OSNITWNUBCE^SOBRI^NBKCNI@IFSRUBHASNJBFICTWFDB	sOBDNS^WRKTBTPNSOKNABFSBTSFJBISSHSOBBDOHBTHArK^TTBT	-WUHJWSbIBU@BSNDSBDOIHEBFSUBKBISKBTTEFTTKNIBWRKTFSNI@UO^SOJTTOFUWT^ISOTCUNQNI@WBUDRTTNHIEHKCSBJWHTONASTJFKBQHDFKPNSO@UNSS^RICBUSHIBT-DHQBUfUSwUHJWSaRSRUNTSNDDNS^TDFWBFSIN@OSIBHIKN@OSTUBAKBDSNI@HIPBSTSUBBSTTOFUW@BHJBSUNDTOFWBTC^IFJNDJHSNHIEKRUNISBITBFICQNEUFISDHKHUWFKBSSBJHCBUID^EBUWRILFBTSOBSND-TA_NICRTSUNFKDKFI@NI@JBDOFINDFKPONUUTBDOHNI@AHHSTSBWTCNTSFISTNUBIT-QHDFKTJFKBQHDFK@UNSS^FICCBBWBDOHNI@BAABDSTNISBITBCBKNQBU^-QHDFKTtSURDSRUBCSBDOIHSUFDLPNSOFWHPBUARKNISUHFICFCUFJFSNDHRSUHABFSRUNI@THJBNISBITBCUHWTPNSOCBBWJFKBQHDFK-LB^PHUCTSBDOIHOFUCSBLLBKBDSUHINDD^EBUWRILDKRECFIDBEFTTT^ISOPFQBIN@OSQNEBTDNS^TDFWBIBHIKN@OSTTHRICSUFDLHTSNICRTSUNFKOFUCEBFS-DHCBiFJBrK^TTBT-EWJ-@BIUBnIWRS-WUHJWSnIWRSsUFDLNITWNUBCE^oFUCSBLL
qNBKKBNDOSSBDOIH	rTBTNJNKFUJRTNDFKQNEBJHHCTS^KB@BIUBNITSURJBIST	-KBSSBUr-NIDKRCBqHDFKaFKTB-FWWqBUTNHIQ-CRUFSNHI--K^UNDT|NISUH
JBDOFINDFKORJz--|QBUTBz-HHHHH-TOOOOOOOO--|ERNKC
RW
BDOHNI@WRKTBz--|CUHW
UBKBISKBTTTRU@Bz-FFFFF--|EUNC@B
NICRTSUNFKBDOHBTz-HHHHHHHNNNNNNN--|DOHURT
EFTTCUHWz-PHHHHHH--|HRSUH
AFCNI@KN@OSz-]]]]]]]--dUBFSBCE^fswKF^BU-OSSWTPPP	FSWKF^BU	DHJ--dHW^UN@OSåŽfLSNTnID	